### ISSUE TITLE
redis_tang not working with redis 0.19.0

### ISSUE THREAD

**Issue by losintikfos** [fakeshadow/tang_rs#4]
Hi guys,

I have upgraded my `redis` version from `0.17` to `0.19` and does not seems to be compatible with `redis_tang`. Is this something that will be considered in future work in the redis_tang project?

Thanks

**Comment by fakeshadow** [comment]
Thanks for the feedback. I would update and make a new release.

**Comment by fakeshadow** [comment]
@losintikfos 
redis_tang 0.2.0 is released.

**Comment by losintikfos** [comment]
@fakeshadow  Whoa! dude that was super quick.

**Comment by fakeshadow** [comment]
> @fakeshadow Whoa! dude that was super quick.

It was mostly straight up update dep version and I didn't make any further test. Please let me know if you have issue on the new release.

**Comment by losintikfos** [comment]
Thanks! I have set my dep to pin master branch so can report errors in the future. So far all working as required.
